# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c558c92ffdc95f227417b44af57f4cbaeccbc3161b271703286f9873acdc0fbb31cae5629329164f35dcda8d1974e78629d0c9e8e497684ad647367759aedcdc

test:
  secret_key_base: 1ffd9cb2589f6ea5c08f92242428cc00fc008b1dc6f6cd86e6b30c6f7f0f9358c3d5e628f068e9763f7e64c0bb2759b2a6fa212e29bd0e8586dfb73a8d438da7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
